// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwamhdcheopornbeitac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13YW1oZGNoZW9wb3JuYmVpdGFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMjE2MjEsImV4cCI6MjA1NzU5NzYyMX0.UcS_DvzTBX_t-ZBGBgL_0IqDG3sbmuPmr1cIplST5Co";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);